---
title: "Fieldmark data"
author: "Adela Sobotkova"
date: "2024-09-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(googlesheets4)
library(tidyverse)
library(mapview)
library(sf)
```


Get data
```{r}
data <- read_csv("../data/Fieldmark/Shelter20240919.csv")
glimpse(data)
data_sf <- data %>% 
    filter(id < 1000) %>% 
  st_as_sf(coords = c("take-point-from-gps_latitude",
                      "take-point-from-gps_longitude"), crs = 4326)

data2 <- read_csv("../data/Fieldmark/Shelter20240921.csv")
data2_sf <- data2 %>% 
  filter(id < 1000) %>% 
 st_as_sf(coords = c("take-point-from-gps_latitude",
                      "take-point-from-gps_longitude"), crs = 4326)

data3 <- read_csv("../data/Fieldmark/Shelter20241005ch.csv")
data3 <- data3[,1:33]
data3_sf <- data3 %>% 
  filter(id < 1000 & id > 292) %>% 
 st_as_sf(coords = c("take-point-from-gps_longitude",
                      "take-point-from-gps_latitude"), crs = 4326)
glimpse(data3)

data4 <- read_csv("../data/Fieldmark/Shelter20241012.csv")
data4 <- data4[,1:33]
data4_sf <- data4 %>% 
  filter(id < 350 & id > 292) %>% #select(id,`take-point-from-gps_longitude`, `take-point-from-gps`)
 st_as_sf(coords = c("take-point-from-gps_latitude",
                      "take-point-from-gps_longitude"), crs = 4326)
names(data4_sf)
names(data3_sf)

mapview(data_sf)
mapview(data2_sf)
mapview(data3_sf)
mapview(data4_sf)
```

Create first week data file
```{r}
mergeddata <- rbind(data_sf, data2_sf)
mergeddata <- mergeddata %>% 
  mutate(id = as.numeric(id)) %>% 
  mutate(day = day(updated)) %>% 
  #select(id) %>% 
  arrange(id)


mergeddata2 <- rbind(data3_sf, data4_sf)
mergeddata2 <- mergeddata2 %>% 
  mutate(id = as.numeric(id)) %>% 
  mutate(day = day(updated)) %>% 
  #select(id) %>% 
  arrange(id)

mapview(mergeddata2, zcol = "day") + mapview(mergeddata, zcol = "day") 


library(lubridate)
mergeddata %>% 
  select(identifier, day, updated) %>% 
  group_by(day) %>%
  tally()
st_write(mergeddata, "../../fieldmark-faims/data/Fieldmark/fieldmark_20240922.geojson")
st_write(mergeddata2, "../../fieldmark-faims/data/Fieldmark/fieldmark_20241012.geojson")
```
# Reload saved data
```{r}
names(data)
data %>% 
  select(identifier, shelter.type, entryway.type, landuse.on.top, landuse.around, geometry) %>% 
  st_write("data/Fieldmark/fieldmark.shp")

data <- st_read("../../fieldmark-faims/data/Fieldmark/fieldmark_20240922.geojson")
data2 <-st_read("../../fieldmark-faims/data/Fieldmark/fieldmark_20241012.geojson") 
glimpse(data)
glimpse(data2)

data$id
data2$id
mapview(data) + mapview(data2) +mapview(shelter)

done <- shelter %>% 
  rename(id = FeatureID) %>% 
  select(id) %>% 
  rbind(data %>% select(id), data2 %>% select(id))

names(data2)%in%names(data)

data24 <- data2 %>% 
#  select(-day) %>% 
  rbind(data)

mapview(data24) # 43 2024 feautres (total 209 features as of 15 October) Where is Tranbjerg??

data24 %>% 
  # st_write("../data/Fieldmark/GC_20241012.geojson")
  mutate(longitude = st_coordinates(.)[,1],
         latitude = st_coordinates(.)[,2]) %>% 
  st_drop_geometry() %>% 
  write_csv("../data/Fieldmark/GC_20241012.csv")
```
# Test of roads
```{r}
streetnames <- st_read("../data/Aarhus_streetnames.geojson")
plot(streetnames$geometry)
mapview(streetnames)
```



